### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''  on save.

### ISSUE THREAD

**Issue by jbarnes7952** [FlipperPA/wagtailmarkdownblock#7]
Got the same error in 3.5.2 and 3.6.4   

From the Streamfield panel in the admin interface, 'markdown'  can be selected and the MDE will start, attempting to save invokes the error.

Wagtailcodeblock is working flawlessly.  Perhaps I've missed something obvious?

```
beautifulsoup4==4.6.0
bleach==2.1.2
certifi==2018.1.18
chardet==3.0.4
Django==1.11.9
django-el-pagination==3.2.3
django-modelcluster==3.1
django-taggit==0.22.2
django-treebeard==4.2.0
djangorestframework==3.6.4
html5lib==0.999999999
idna==2.6
Markdown==2.6.11
Pillow==5.0.0
pkg-resources==0.0.0
pytz==2017.3
requests==2.18.4
six==1.11.0
Unidecode==1.0.22
urllib3==1.22
wagtail==1.13.1
wagtail-markdown==0.5a1
wagtailcodeblock==0.4.2
wagtailmarkdownblock==0.3.1
webencodings==0.5.1
Willow==1.0
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailadmin/urls/__init__.py", line 96, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailadmin/decorators.py", line 31, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailadmin/views/pages.py", line 321, in edit
    if form.is_valid() and not page.locked:
  File "/usr/local/lib/python3.6/site-packages/modelcluster/forms.py", line 259, in is_valid
    form_is_valid = super(ClusterForm, self).is_valid()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 384, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 396, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailcore/blocks/base.py", line 523, in value_from_datadict
    return self.block_def.value_from_datadict(data, files, name)
  File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 165, in value_from_datadict
    int(data['%s-%d-order' % (prefix, i)]),
ValueError: invalid literal for int() with base 10: 
```

models.py
```
 33     body = StreamField([                                                                                                                               
 34         ('heading', blocks.CharBlock(classname="full title")),                                                                                         
 35         ('paragraph', blocks.RichTextBlock()),                                                                                                         
 36         ('image', ImageChooserBlock()),                                                                                                                
 37         ('code', CodeBlock(label='Code')),                                                                                                             
 38         ('markdown', MarkdownBlock()),                                                                                                                 
 39     ])

```

**Comment by FlipperPA** [comment]
I'm sorry, but I've been unable to reproduce the error. I installed the same exact requirements you included (omitting `pkg-resources==0.0.0`) into a brand new Django project, and created the same body like this:

```python
from wagtail.wagtailcore import blocks
from wagtail.wagtailcore.models import Page
from wagtail.wagtailcore.fields import StreamField
from wagtail.wagtailimages.blocks import ImageChooserBlock
from wagtail.wagtailadmin.edit_handlers import FieldPanel, StreamFieldPanel

from wagtailcodeblock.blocks import CodeBlock
from wagtailmarkdownblock.blocks import MarkdownBlock



class MyPage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="fulltitle")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
        ('code', CodeBlock(label='Code')),
        ('markdown', MarkdownBlock()),
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body', classname="full"),
    ]
```

I then made migrations, migrated, and brought up a page, put in some content, and saved. It all seems to work:

![image](https://user-images.githubusercontent.com/68164/35705635-0b8a3a00-0771-11e8-9ff3-659af212bd1e.png)

It looks like the problem might be somewhere else in your stack? Here's my Python version and a `pip freeze`, in case it helps. I also run this on Python 3.5, so I don't think it is a question of the Python version. If you'd like, I can ZIP up the temporary project I threw together, including the SQLite DB, and send it your way.

```
(mdb) [vagrant@vagrant mdb]$ python --version
Python 3.6.4
(mdb) [vagrant@vagrant mdb]$ pip freeze
beautifulsoup4==4.6.0
bleach==2.1.2
certifi==2018.1.18
chardet==3.0.4
Django==1.11.9
django-el-pagination==3.2.3
django-modelcluster==3.1
django-taggit==0.22.2
django-treebeard==4.2.0
djangorestframework==3.6.4
html5lib==0.999999999
idna==2.6
Markdown==2.6.11
Pillow==5.0.0
pytz==2017.3
requests==2.18.4
six==1.11.0
Unidecode==1.0.22
urllib3==1.22
wagtail==1.13.1
wagtail-markdown==0.5a1
wagtailcodeblock==0.4.2
-e git+git@github.com:FlipperPA/wagtailmarkdownblock.git@d49a342f321e222a889654c139ba65522bc821c4#egg=wagtailmarkdownblock
webencodings==0.5.1
Willow==1.0
```

**Comment by FlipperPA** [comment]
Just a thought: were you using the MarkdownBlock from `wagtail-markdown`? That'd be here: https://github.com/torchbox/wagtail-markdown

Check your `import` statement to see where you're getting MarkdownBlock from?

**Comment by jbarnes7952** [comment]
That's exactly what I did.  Thanks.  Also, I needed to install the MDE.

**Comment by jbarnes7952** [comment]
I am still getting the same error after removing everything, so I moved to a fresh Docker image and have been able to recreate there.

The Dockerfile installs wagtail,  installs wagtailmarkdownblock via pip.  (maybe this is where I'm erring?)
It then copies the attached models.py and migrates.

Dockerfile.python

```
FROM python
RUN pip install wagtail
WORKDIR /app
RUN wagtail start mysite
WORKDIR /app/mysite
RUN pip install git+https://github.com/FlipperPA/wagtailmarkdownblock
COPY models.py home/models.py
RUN python manage.py makemigrations && python manage.py migrate
RUN echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin', 'admin@example.com', 'nimda')" | python manage.py shell
CMD python manage.py runserver 0.0.0.0:8000
```

models.py

```
from __future__ import absolute_import, unicode_literals
from django.db import models
from wagtail.wagtailcore.models import Page

from wagtail.wagtailcore import blocks
from wagtail.wagtailcore.fields import StreamField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, StreamFieldPanel

from wagtailmarkdownblock.blocks import MarkdownBlock


class HomePage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="fulltitle")),
        ('markdown', MarkdownBlock()),
    ], null=True, blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel('body', classname="full"),
    ]

```

I also tried running from an Ubuntu container instead of the Python one:

Dockerfile.ubuntu

```
FROM ubuntu 
RUN apt-get update && apt-get install -y python3 python3-dev python3-pip git
RUN pip3 install wagtail
WORKDIR /app
RUN wagtail start mysite
WORKDIR /app/mysite
RUN pip3 install git+https://github.com/FlipperPA/wagtailmarkdownblock
COPY models.py home/models.py
RUN python3 manage.py makemigrations && python3 manage.py migrate
RUN echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin', 'admin@example.com', 'nimda')" | python3 manage.py shell
CMD python3 manage.py runserver 0.0.0.0:8000
```


docker build -t test -f Dockerfile.python . && docker run -d --rm -p 8000:8000 test
